# Generated by Django 3.1.6 on 2021-03-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('heading', models.CharField(max_length=300)),
                ('details', models.TextField()),
                ('photo', models.ImageField(upload_to='news_photos')),
                ('reporter', models.CharField(max_length=80)),
            ],
        ),
    ]
