# Generated by Django 3.1.2 on 2021-03-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210328_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='recent',
            field=models.BooleanField(default=False),
        ),
    ]
