# Generated by Django 4.0.6 on 2022-07-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_readlater_readlaterselve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readlaterselve',
            name='user',
        ),
        migrations.DeleteModel(
            name='ReadLater',
        ),
        migrations.DeleteModel(
            name='ReadLaterSelve',
        ),
    ]
